# Py_particules demonstrator

In [1]:
import sys
import os
import numpy as np

module_dir = os.path.abspath(os.path.join(os.path.dirname(__name__), "../build/lib"))
sys.path.insert(0, module_dir)

from py_src.solver import Solver

### Initialize particle solver with particles list 1 containing 5 particles

In [2]:
nemo = Solver("NEMO","euler",1,5)

Solver NEMO created with method euler


In [3]:
print(nemo)

Current iteration: 0 and simulation time: 0.0


#### Advance 5 iterations in time with dt=0.1

In [4]:
nemo.advance(5,0.1)

Advancement reached iteration: 5 and Total simulation time: 0.5


#### Advance 3 iterations with dt=0.5

In [5]:
nemo.advance(3,0.5)

Advancement reached iteration: 8 and Total simulation time: 2.0


#### Show current values

In [6]:
ids, pos, vels = nemo.get()

print(ids)
print(' --- ')
print(pos)
print(' --- ')
print(vels)

Get particles values at  Current iteration: 8 and simulation time: 2.0 

[1 2 3 4 5]
 --- 
[ 4.291052   -3.5042272  -4.2177386   0.45768696  1.4923651  -0.8106724
 -4.851965    1.667918    2.0754068  -4.315059    3.0380096  -3.2782483
  2.7240586   0.81905437  4.149972  ]
 --- 
[-0.9543897   0.15168834  0.8202374  -0.2904042  -0.9870573  -0.12237525
  0.43249285  0.13865912 -0.9499291  -0.562626   -0.9939077   0.9364946
  0.55727696  0.2724806  -0.21392417]


#### Write results -- show content of written file

In [7]:
nemo.write()
!cat Part_008.dat

 Write results in Part_008.dat
  1   0.4291052E+01 -0.3504227E+01 -0.4217739E+01 -0.9543897E+00  0.1516883E+00  0.8202374E+00                                                                                                         
  2   0.4576870E+00  0.1492365E+01 -0.8106724E+00 -0.2904042E+00 -0.9870573E+00 -0.1223752E+00                                                                                                         
  3  -0.4851965E+01  0.1667918E+01  0.2075407E+01  0.4324929E+00  0.1386591E+00 -0.9499291E+00                                                                                                         
  4  -0.4315059E+01  0.3038010E+01 -0.3278248E+01 -0.5626260E+00 -0.9939077E+00  0.9364946E+00                                                                                                         
  5   0.2724059E+01  0.8190544E+00  0.4149972E+01  0.5572770E+00  0.2724806E+00 -0.2139242E+00                                                                           

#### Advance again a bit and show modifications of values

In [8]:
nemo.advance(2,0.5)
nemo.get()

Advancement reached iteration: 10 and Total simulation time: 3.0
Get particles values at  Current iteration: 10 and simulation time: 3.0 



(array([1, 2, 3, 4, 5], dtype=int32),
 array([ 3.3366623 , -3.3525386 , -3.3975015 ,  0.16728276,  0.5053078 ,
        -0.93304765, -4.4194717 ,  1.806577  ,  1.1254776 , -4.877685  ,
         2.0441017 , -2.3417535 ,  3.2813354 ,  1.091535  ,  3.9360476 ],
       dtype=float32),
 array([-0.9543897 ,  0.15168834,  0.8202374 , -0.2904042 , -0.9870573 ,
        -0.12237525,  0.43249285,  0.13865912, -0.9499291 , -0.562626  ,
        -0.9939077 ,  0.9364946 ,  0.55727696,  0.2724806 , -0.21392417],
       dtype=float32))

#### Impose new values -- show changes

In [9]:
ids = np.array([2,4,5])
poss = np.array([5.0,4.0,3.0,1.0,1.0,1.0,-5.0,-4.0,-3.0])
vels = np.array([-0.1,0.2,-0.3,0.8,0.8,0.8,0.5,0.5,0.5])
nemo.set(ids,poss,vels)


Imposing values at  Current iteration: 10 and simulation time: 3.0 



In [10]:
nemo.get()

Get particles values at  Current iteration: 10 and simulation time: 3.0 



(array([1, 2, 3, 4, 5], dtype=int32),
 array([ 3.3366623, -3.3525386, -3.3975015,  5.       ,  4.       ,
         3.       , -4.4194717,  1.806577 ,  1.1254776,  1.       ,
         1.       ,  1.       , -5.       , -4.       , -3.       ],
       dtype=float32),
 array([-0.9543897 ,  0.15168834,  0.8202374 , -0.1       ,  0.2       ,
        -0.3       ,  0.43249285,  0.13865912, -0.9499291 ,  0.8       ,
         0.8       ,  0.8       ,  0.5       ,  0.5       ,  0.5       ],
       dtype=float32))

In [11]:
# free memory
del nemo
!rm Part*

 Particle list deallocated
